name: Build Gradle

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: check ktlint format
        run: ./gradlew ktlintCheck
      
      - name: assemble with Gradle
        run: ./gradlew assemble

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          // override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"

      - uses: actions/upload-artifact@v2
        with:
          name: release apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
