name: Code Coverage

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coverage:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Test coverage with Gradle
        run: ./gradlew cleanTest test jacocoTestReport -x app:connectedDebugAndroidTest

      - uses: codecov/codecov-action@v1
        with:
          files: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          verbose: true
