name: Code Coverage

on: [push, pull_request]

jobs:
  coverage:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Test coverage with Gradle
        run: ./gradlew cleanTest test jacocoTestReportDebug

      - uses: codecov/codecov-action@v1
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true